<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Lamp" Id="{d4c89d15-b770-45c8-b729-af82b526254a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Lamp
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_nPowerConsumption	: UDINT := 1234;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="nPowerConsumption" Id="{1fe18b4a-5755-4893-8591-56a3b6f7f5c9}">
      <Declaration><![CDATA[PROPERTY nPowerConsumption : UDINT]]></Declaration>
      <Get Name="Get" Id="{2f81a754-0162-489e-af33-00e731e88eed}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[nPowerConsumption := _nPowerConsumption;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_Lamp">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Lamp.nPowerConsumption.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>